import { Question } from '../hooks/useTrivia';

export const QUESTIONS: Question[] = [
  {
    'level': 'easy',
    'question':
      'What is the name of the coffee shop in Friends where the main characters frequently hang out?',
    'unlockedClue': "It's named after a type of coffee bean",
    'answers': ['Central Perk', 'The Grind', "Java Joe's", 'Coffee Corner'],
    'correctAnswer': 'Central Perk',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question':
      'In The Office (US), what is the name of the paper company where the characters work?',
    'unlockedClue': "It's named after a type of paper product",
    'answers': [
      'Dunder Mifflin',
      'Schrute Farms',
      'Vance Refrigeration',
      'Michael Scott Paper Company',
    ],
    'correctAnswer': 'Dunder Mifflin',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Breaking Bad, what is Walter White's high school chemistry teacher nickname?",
    'unlockedClue': "It's related to his cooking abilities",
    'answers': ['Mr. White', 'Heisenberg', 'The Cook', 'Walt'],
    'correctAnswer': 'Heisenberg',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question':
      "What spell does Hermione use to fix Harry's glasses in the first Harry Potter movie?",
    'unlockedClue': "It's a repairing charm",
    'answers': ['Reparo', 'Expelliarmus', 'Wingardium Leviosa', 'Alohomora'],
    'correctAnswer': 'Reparo',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Crown, what is the Queen's private secretary's name in the early seasons?",
    'unlockedClue': "He's played by Harry Hadden-Paton",
    'answers': ['Martin Charteris', 'Tommy Lascelles', 'Michael Adeane', 'Edward Ford'],
    'correctAnswer': 'Tommy Lascelles',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In E.T. the Extra-Terrestrial, what does E.T. say he wants to do?',
    'unlockedClue': "It's about contacting his people",
    'answers': ['Phone home', 'Go home', 'Find home', 'Call home'],
    'correctAnswer': 'Phone home',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In BoJack Horseman, what is BoJack's species?",
    'unlockedClue': "He's a large mammal that people ride",
    'answers': ['Horse', 'Dog', 'Cat', 'Pig'],
    'correctAnswer': 'Horse',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Jaws, what is the shark hunter's name?",
    'unlockedClue': 'He has a memorable speech about the USS Indianapolis',
    'answers': ['Quint', 'Hooper', 'Brody', 'Vaughn'],
    'correctAnswer': 'Quint',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Utopia (UK), what is the name of the graphic novel everyone is searching for?',
    'unlockedClue': "It's the title of the show",
    'answers': ['Utopia', 'The Network', 'Dystopia', 'Jessica Hyde'],
    'correctAnswer': 'Utopia',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'In Ghostbusters, what is the name of the EPA official who shuts down the Ghostbusters?',
    'unlockedClue': "He's played by William Atherton",
    'answers': ['Walter Peck', 'Louis Tully', 'Dana Barrett', 'Janine Melnitz'],
    'correctAnswer': 'Walter Peck',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Breakfast Club, how many students are in detention?',
    'unlockedClue': "It's the same number as the main characters",
    'answers': ['Five', 'Four', 'Six', 'Three'],
    'correctAnswer': 'Five',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Deadpool, what is Wade Wilson's girlfriend's name?",
    'unlockedClue': 'She works as an escort and her name is also a flower',
    'answers': ['Vanessa', 'Domino', 'Copycat', 'Shiklah'],
    'correctAnswer': 'Vanessa',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Thick of It, what is Malcolm Tucker's favorite swear word combination?",
    'unlockedClue': 'It involves omnishambles',
    'answers': ['Omnishambles', 'Clusterfuck', 'Shitshow', 'Cockup'],
    'correctAnswer': 'Omnishambles',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Titanic, what is the name of the ship?',
    'unlockedClue': "It's the title of the movie",
    'answers': ['RMS Titanic', 'HMS Titanic', 'SS Titanic', 'USS Titanic'],
    'correctAnswer': 'RMS Titanic',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Anchorman, what percentage of the time does Sex Panther work every time?',
    'unlockedClue': "It's a mathematical impossibility",
    'answers': [
      '60% of the time, it works every time',
      '50% of the time, it works every time',
      '80% of the time, it works every time',
      '70% of the time, it works every time',
    ],
    'correctAnswer': '60% of the time, it works every time',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Shrek, what type of creature is Shrek?',
    'unlockedClue': "He's a green monster that lives in a swamp",
    'answers': ['Ogre', 'Troll', 'Giant', 'Monster'],
    'correctAnswer': 'Ogre',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Mindhunter, what is Holden Ford's partner's name?",
    'unlockedClue': "He's the more experienced agent played by Holt McCallany",
    'answers': ['Bill Tench', 'Greg Lougher', 'Jim Barney', 'Roy Carver'],
    'correctAnswer': 'Bill Tench',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Terminator 2, what does the T-800 say before jumping into the molten steel?',
    'unlockedClue': "It's about understanding human emotion",
    'answers': [
      'I know now why you cry',
      'Hasta la vista, baby',
      "I'll be back",
      'Come with me if you want to live',
    ],
    'correctAnswer': 'I know now why you cry',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Monsters, Inc., what powers the city?',
    'unlockedClue': "It comes from children's reactions",
    'answers': ['Screams', 'Fear', 'Laughter', 'Dreams'],
    'correctAnswer': 'Screams',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Big Lebowski, what does The Dude drink?',
    'unlockedClue': "It's a cocktail made with vodka and cream",
    'answers': ['White Russian', 'Black Russian', 'Mudslide', 'Milk'],
    'correctAnswer': 'White Russian',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Broadchurch, what is DI Alec Hardy's heart condition?",
    'unlockedClue': 'It affects his heart rhythm',
    'answers': ['Arrhythmia', 'Heart attack', 'Angina', 'Cardiomyopathy'],
    'correctAnswer': 'Arrhythmia',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Home Alone, where is Kevin's family going on vacation?",
    'unlockedClue': "It's a European city famous for its Eiffel Tower",
    'answers': ['Paris', 'London', 'Rome', 'Madrid'],
    'correctAnswer': 'Paris',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In There Will Be Blood, what does Daniel Plainview say at the end?',
    'unlockedClue': 'It involves being finished',
    'answers': ["I'm finished", "I'm done", "It's over", "That's all"],
    'correctAnswer': "I'm finished",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Frozen, what is Elsa's power?",
    'unlockedClue': 'She can create winter weather',
    'answers': ['Ice and snow', 'Fire', 'Water', 'Wind'],
    'correctAnswer': 'Ice and snow',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Peaky Blinders, what is tattooed on Arthur Shelby's chest?",
    'unlockedClue': "It's a religious symbol",
    'answers': ['Jesus Christ', 'Cross', 'Angel', 'Bible verse'],
    'correctAnswer': 'Jesus Christ',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      "In Scarface, what does Tony Montana's mansion have that he's particularly proud of?",
    'unlockedClue': "It's in his bathroom and very extravagant",
    'answers': ['Golden bathtub', 'Golden toilet', 'Marble floors', 'Crystal chandelier'],
    'correctAnswer': 'Golden bathtub',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Incredibles, what is Mr. Incredible's real name?",
    'unlockedClue': 'His first name is Bob',
    'answers': ['Bob Parr', 'Robert Incredible', 'Bob Super', 'Robert Hero'],
    'correctAnswer': 'Bob Parr',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In No Country for Old Men, what weapon does Anton Chigurh use?',
    'unlockedClue': "It's typically used to kill cattle",
    'answers': ['Captive bolt pistol', 'Shotgun', 'Silenced pistol', 'Knife'],
    'correctAnswer': 'Captive bolt pistol',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Doctor Who, what is the Doctor's real name?",
    'unlockedClue': "It's a mystery that's rarely revealed",
    'answers': ['Never fully revealed', 'Theta Sigma', 'John Smith', 'The Doctor'],
    'correctAnswer': 'Never fully revealed',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In WALL-E, what does WALL-E collect?',
    'unlockedClue': 'He organizes and treasures these items',
    'answers': ['Trinkets and treasures', 'Plants', 'Batteries', 'Metal scraps'],
    'correctAnswer': 'Trinkets and treasures',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Reservoir Dogs, what color is Mr. Pink's real identity never revealed as?",
    'unlockedClue': 'The actors are known by color-coded names',
    'answers': ['His real name is never revealed', 'Steve Buscemi', 'Pink', 'Unknown'],
    'correctAnswer': 'His real name is never revealed',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Up, what is the old man's name?",
    'unlockedClue': "He's voiced by Ed Asner",
    'answers': ['Carl Fredricksen', 'Russell', 'Charles Muntz', 'Dug'],
    'correctAnswer': 'Carl Fredricksen',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question':
      'In The Leftovers, what is the name of the town where most of the action takes place?',
    'unlockedClue': "It's in New York state",
    'answers': ['Mapleton', 'Miracle', 'Jarden', 'Kingston'],
    'correctAnswer': 'Mapleton',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In American Beauty, what does Lester Burnham become obsessed with?',
    'unlockedClue': "She's his daughter's friend",
    'answers': ['Angela Hayes', 'Jane Burnham', 'Carolyn Burnham', 'Fitness'],
    'correctAnswer': 'Angela Hayes',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Moana, what does Moana return to Te Fiti?',
    'unlockedClue': "It's a green stone",
    'answers': ['The heart of Te Fiti', 'A pearl', 'A shell', 'A gem'],
    'correctAnswer': 'The heart of Te Fiti',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'In Heat, how long is the famous coffee shop conversation between De Niro and Pacino?',
    'unlockedClue': "It's a substantial portion of the film",
    'answers': ['About 15 minutes', '5 minutes', '30 minutes', '45 minutes'],
    'correctAnswer': 'About 15 minutes',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Line of Duty, what does AC-12 stand for?',
    'unlockedClue': "It's an anti-corruption unit",
    'answers': [
      'Anti-Corruption Unit 12',
      'Armed Crime Unit 12',
      'Active Crime Unit 12',
      'Anti-Crime Unit 12',
    ],
    'correctAnswer': 'Anti-Corruption Unit 12',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Inside Out, what are the five emotions?',
    'unlockedClue': 'Joy is one of them, along with four others',
    'answers': [
      'Joy, Sadness, Anger, Fear, Disgust',
      'Joy, Sadness, Anger, Love, Hate',
      'Happy, Sad, Mad, Scared, Confused',
      'Joy, Sorrow, Rage, Terror, Revulsion',
    ],
    'correctAnswer': 'Joy, Sadness, Anger, Fear, Disgust',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Departed, who is the rat?',
    'unlockedClue': 'There are multiple rats in this movie',
    'answers': [
      'Both Colin Sullivan and Billy Costigan',
      'Colin Sullivan',
      'Billy Costigan',
      'Frank Costello',
    ],
    'correctAnswer': 'Both Colin Sullivan and Billy Costigan',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Coco, what is Miguel's family's profession?",
    'unlockedClue': 'They work with leather and feet',
    'answers': ['Shoemakers', 'Musicians', 'Bakers', 'Farmers'],
    'correctAnswer': 'Shoemakers',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Americans, what are Philip and Elizabeth's cover identities' surnames?",
    'unlockedClue': "It's a common American surname",
    'answers': ['Jennings', 'Smith', 'Johnson', 'Williams'],
    'correctAnswer': 'Jennings',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Goodfellas, what does Henry Hill say you can never be if you're Irish?",
    'unlockedClue': "It's about organized crime membership",
    'answers': ['A made guy', 'A wiseguy', 'A goodfella', 'In the family'],
    'correctAnswer': 'A made guy',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Zootopia, what kind of animal is Judy Hopps?',
    'unlockedClue': "She's a small, fast hopping mammal",
    'answers': ['Rabbit', 'Fox', 'Sheep', 'Mouse'],
    'correctAnswer': 'Rabbit',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Casino, what happens to Ace Rothstein's car?",
    'unlockedClue': 'It involves an explosive device',
    'answers': ['It explodes with a car bomb', 'It gets stolen', 'It crashes', 'It gets impounded'],
    'correctAnswer': 'It explodes with a car bomb',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Killing Eve, what is Villanelle's real name?",
    'unlockedClue': "It's revealed in later seasons and is Russian",
    'answers': ['Oksana Astankova', 'Katarina Volkov', 'Natasha Petrov', 'Irina Kozlov'],
    'correctAnswer': 'Oksana Astankova',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Ratatouille, what kind of animal is Remy?',
    'unlockedClue': "He's a rodent that can cook",
    'answers': ['Rat', 'Mouse', 'Hamster', 'Guinea pig'],
    'correctAnswer': 'Rat',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Wolf of Wall Street, what drug does Jordan Belfort get addicted to?',
    'unlockedClue': "It's a sedative that causes memory problems",
    'answers': ['Quaaludes', 'Cocaine', 'Heroin', 'Alcohol'],
    'correctAnswer': 'Quaaludes',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Encanto, who doesn't get a magical gift?",
    'unlockedClue': "She's the main character",
    'answers': ['Mirabel', 'Isabela', 'Luisa', 'Bruno'],
    'correctAnswer': 'Mirabel',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Succession, what is the name of the Waystar Royco cruise division scandal?',
    'unlockedClue': 'It involves covering up crimes on cruise ships',
    'answers': [
      'Mo-Lester and the Cruises',
      'The Cruise Scandal',
      'Waystar Cruises',
      'Royal Caribbean',
    ],
    'correctAnswer': 'Mo-Lester and the Cruises',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Django Unchained, what is Django's wife's name?",
    'unlockedClue': 'She shares her name with a German mythological figure',
    'answers': ['Broomhilda', 'Brunhilde', 'Hildi', 'Brenda'],
    'correctAnswer': 'Broomhilda',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Avengers, what does Tony Stark say about Shawarma?',
    'unlockedClue': 'He wants to try it after the battle',
    'answers': [
      "There's a Shawarma joint about two blocks from here",
      'I want Shawarma',
      "Let's get Shawarma",
      'Shawarma sounds good',
    ],
    'correctAnswer': "There's a Shawarma joint about two blocks from here",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question':
      'In Fleabag, what does the Priest say that makes Fleabag realize he can see her looking at the camera?',
    'unlockedClue': "It's about where she goes",
    'answers': [
      "Where'd you just go?",
      'Are you talking to someone?',
      'Who are you looking at?',
      "What's over there?",
    ],
    'correctAnswer': "Where'd you just go?",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'In Inglourious Basterds, how many fingers does the British spy hold up incorrectly?',
    'unlockedClue': 'It gives away his nationality at the bar',
    'answers': ['Three', 'Two', 'Four', 'Five'],
    'correctAnswer': 'Three',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Turning Red, what animal does Mei turn into?',
    'unlockedClue': "It's a large red furry mammal",
    'answers': ['Red Panda', 'Bear', 'Fox', 'Wolf'],
    'correctAnswer': 'Red Panda',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Once Upon a Time in Hollywood, what TV Western show is Rick Dalton known for?',
    'unlockedClue': "It's a fictional Western series",
    'answers': ['Bounty Law', 'Lancer', 'The Virginian', 'Gunsmoke'],
    'correctAnswer': 'Bounty Law',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Euphoria, what is Rue's full name?",
    'unlockedClue': "It's revealed to be a longer, more formal name",
    'answers': ['Ruby Bennett', 'Ruth Bennett', 'Rachel Bennett', 'Rebecca Bennett'],
    'correctAnswer': 'Ruby Bennett',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Luca, what do Luca and Alberto turn into when they get wet?',
    'unlockedClue': "They're sea creatures",
    'answers': ['Sea monsters', 'Fish', 'Mermaids', 'Octopi'],
    'correctAnswer': 'Sea monsters',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Parasite, what smell does Ki-taek associate with Mr. Park?',
    'unlockedClue': 'It crosses a line when mentioned',
    'answers': [
      'The smell that crosses the line',
      'Rich people smell',
      'Expensive cologne',
      'Clean soap',
    ],
    'correctAnswer': 'The smell that crosses the line',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Soul, what is Joe Gardner's dream job?",
    'unlockedClue': "He's a music teacher who wants to perform",
    'answers': ['Jazz musician', 'Symphony conductor', 'Music producer', 'Piano teacher'],
    'correctAnswer': 'Jazz musician',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Queen's Gambit, what is Beth Harmon's adoptive mother's maiden name?",
    'unlockedClue': 'She mentions it when talking about her past',
    'answers': ['Wheatley', 'Deardorff', 'Ganz', 'Shaibel'],
    'correctAnswer': 'Wheatley',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Knives Out, what is the name of the Thrombey family mansion?',
    'unlockedClue': "It's mentioned several times throughout the film",
    'answers': [
      'The Thrombey Estate',
      'Knives Out Manor',
      'The Drysdale House',
      "It's never specifically named",
    ],
    'correctAnswer': "It's never specifically named",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Spider-Man: Into the Spider-Verse, what is Miles Morales' uncle's name?",
    'unlockedClue': 'He becomes the Prowler',
    'answers': ['Aaron', 'Marcus', 'Andre', 'Carlos'],
    'correctAnswer': 'Aaron',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Favourite, what does Queen Anne obsess over besides Sarah?',
    'unlockedClue': "They're small, fluffy animals",
    'answers': ['Rabbits', 'Ducks', 'Cats', 'Dogs'],
    'correctAnswer': 'Rabbits',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Barry, what is the name of Barry's acting class teacher?",
    'unlockedClue': "He's played by Henry Winkler",
    'answers': ['Gene Cousineau', 'Monroe Fuches', 'NoHo Hank', 'Detective Moss'],
    'correctAnswer': 'Gene Cousineau',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Mandalorian, what is the Mandalorian's preferred weapon?",
    'unlockedClue': 'It fires energy bolts and is his signature weapon',
    'answers': ['Blaster rifle', 'Lightsaber', 'Blaster pistol', 'Vibroblade'],
    'correctAnswer': 'Blaster rifle',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      "In Jojo Rabbit, what does Jojo's imaginary Hitler tell him to do with the hand grenades?",
    'unlockedClue': "It's at a Hitler Youth training exercise",
    'answers': [
      'Throw them at the tree',
      'Give them to the instructor',
      'Hide them',
      'Run away with them',
    ],
    'correctAnswer': 'Throw them at the tree',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In WandaVision, what decade does the first episode parody?',
    'unlockedClue': "It's the era of I Love Lucy and early sitcoms",
    'answers': ['1950s', '1960s', '1940s', '1970s'],
    'correctAnswer': '1950s',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Russian Doll, what is Nadia's cat's name?",
    'unlockedClue': "It's named after a character from The Lion King",
    'answers': ['Oatmeal', 'Simba', 'Mufasa', 'Nala'],
    'correctAnswer': 'Oatmeal',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In 1917, what message must the two soldiers deliver?',
    'unlockedClue': "It's about calling off an attack",
    'answers': ['Cancel the attack', 'Retreat immediately', 'Send reinforcements', 'Hold position'],
    'correctAnswer': 'Cancel the attack',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Bridgerton, what is Daphne's last name?",
    'unlockedClue': "She's part of the main family the show is named after",
    'answers': ['Bridgerton', 'Hastings', 'Featherington', 'Sheffield'],
    'correctAnswer': 'Bridgerton',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Ford v Ferrari, what is the name of the Ford race car?',
    'unlockedClue': 'It has a number associated with Gulf Oil colors',
    'answers': ['GT40', 'Mustang', 'Cobra', 'Falcon'],
    'correctAnswer': 'GT40',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Lovecraft Country, what is the name of the guidebook for Black travelers?',
    'unlockedClue': "It's a real historical guidebook referenced in the show",
    'answers': [
      'The Safe Negro Travel Guide',
      'The Green Book',
      'The Black Travel Guide',
      'The Motorist Guide',
    ],
    'correctAnswer': 'The Safe Negro Travel Guide',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Squid Game, what is the first game played?',
    'unlockedClue': 'It involves a doll and staying still',
    'answers': ['Red Light, Green Light', 'Tug of War', 'Marbles', 'Hopscotch'],
    'correctAnswer': 'Red Light, Green Light',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Nomadland, what does Fern live in?',
    'unlockedClue': "It's a mobile home that she drives",
    'answers': ['A van', 'An RV', 'A trailer', 'A truck'],
    'correctAnswer': 'A van',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Ted Lasso, what sport does Ted coach in England?',
    'unlockedClue': "It's not American football",
    'answers': ['Soccer/Football', 'Rugby', 'Cricket', 'Tennis'],
    'correctAnswer': 'Soccer/Football',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Mare of Easttown, what is Mare's maiden name?",
    'unlockedClue': "It's revealed when discussing her family history",
    'answers': ['Sheehan', 'Zabel', 'Carroll', 'Ross'],
    'correctAnswer': 'Sheehan',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Trial of the Chicago 7, how many defendants were there originally?',
    'unlockedClue': "It's one more than the famous seven",
    'answers': ['Eight', 'Seven', 'Six', 'Nine'],
    'correctAnswer': 'Eight',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Witcher, what is Geralt's horse's name?",
    'unlockedClue': "It's a type of root vegetable",
    'answers': ['Roach', 'Carrot', 'Turnip', 'Radish'],
    'correctAnswer': 'Roach',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Sound of Metal, what instrument does Ruben play?',
    'unlockedClue': "He's in a metal band and it's part of the rhythm section",
    'answers': ['Drums', 'Guitar', 'Bass', 'Keyboard'],
    'correctAnswer': 'Drums',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      "What is the name of the fictional metal in the Marvel Universe that makes up Captain America's shield?",
    'unlockedClue': "It's known for absorbing vibrations",
    'answers': ['Vibranium', 'Adamantium', 'Unobtainium', 'Beskar'],
    'correctAnswer': 'Vibranium',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Simpsons, what is the name of Homer's favorite beer?",
    'unlockedClue': 'It sounds like a exclamation of annoyance',
    'answers': ['Duff', 'Budweiser', 'Krusty Beer', 'Springfield Ale'],
    'correctAnswer': 'Duff',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Wire, what is Omar Little's signature weapon of choice?",
    'unlockedClue': "It's an old-fashioned hunting weapon",
    'answers': ['Shotgun', 'Pistol', 'Rifle', 'Crossbow'],
    'correctAnswer': 'Shotgun',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      "What movie features the famous line 'I'm gonna make him an offer he can't refuse'?",
    'unlockedClue': "It's about an Italian-American crime family",
    'answers': ['The Godfather', 'Scarface', 'Goodfellas', 'Casino'],
    'correctAnswer': 'The Godfather',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Game of Thrones, what is the motto of House Stark?',
    'unlockedClue': "It's a warning about the changing seasons",
    'answers': ['Winter is Coming', 'Hear Me Roar', 'Fire and Blood', 'Growing Strong'],
    'correctAnswer': 'Winter is Coming',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Arrested Development, what is the name of the family's frozen banana stand?",
    'unlockedClue': "There's always money in it",
    'answers': [
      'The Banana Stand',
      "Bluth's Original Frozen Banana",
      'Big Yellow Joint',
      "Banana Joe's",
    ],
    'correctAnswer': "Bluth's Original Frozen Banana",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Peep Show, what is the name of Mark's favorite historical period?",
    'unlockedClue': 'It involves a specific war era',
    'answers': ['World War II', 'Medieval Times', 'Roman Empire', 'Victorian Era'],
    'correctAnswer': 'World War II',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'What is the name of the spaceship in Firefly?',
    'unlockedClue': "It's named after a type of peace",
    'answers': ['Serenity', 'Enterprise', 'Millennium Falcon', 'Discovery'],
    'correctAnswer': 'Serenity',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In It's Always Sunny in Philadelphia, what is the name of the bar the gang owns?",
    'unlockedClue': "It's named after an Irish city",
    'answers': ["Paddy's Pub", "MacLaren's", 'Cheers', "Moe's Tavern"],
    'correctAnswer': "Paddy's Pub",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Big Bang Theory, what is Sheldon's favorite number?",
    'unlockedClue':
      "It's the answer to life, the universe, and everything according to Douglas Adams",
    'answers': ['73', '42', '137', 'Pi'],
    'correctAnswer': '73',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Black Mirror, what is the name of the dating app featured in 'Hang the DJ'?",
    'unlockedClue': "It's a simple, generic name for a dating system",
    'answers': ['System', 'The Coach', 'Match', 'Connect'],
    'correctAnswer': 'System',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "What movie popularized the phrase 'Nobody puts Baby in a corner'?",
    'unlockedClue': "It's about dancing and summer romance",
    'answers': ['Dirty Dancing', 'Footloose', 'Flashdance', 'Saturday Night Fever'],
    'correctAnswer': 'Dirty Dancing',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Parks and Recreation, what is Leslie Knope's favorite food?",
    'unlockedClue': "It's a breakfast food covered in syrup",
    'answers': ['Waffles', 'Pancakes', 'French Toast', 'Bacon'],
    'correctAnswer': 'Waffles',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In The IT Crowd, what does IT stand for according to the show?',
    'unlockedClue': "It's the typical meaning in computing",
    'answers': [
      'Information Technology',
      'Internet Things',
      'Internal Technical',
      'Integrated Technology',
    ],
    'correctAnswer': 'Information Technology',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'What is the name of the fictional band in That Thing You Do!?',
    'unlockedClue': "They're named after a specific time unit",
    'answers': ['The Oneders', 'The Wonders', 'The Minutes', 'The Seconds'],
    'correctAnswer': 'The Oneders',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Stranger Things, what is Eleven's favorite food?",
    'unlockedClue': "It's a frozen breakfast pastry",
    'answers': ['Eggo Waffles', 'Pop Tarts', 'Toaster Strudel', 'Frozen Pancakes'],
    'correctAnswer': 'Eggo Waffles',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'In Monty Python and the Holy Grail, what is the airspeed velocity of an unladen swallow?',
    'unlockedClue': "The answer depends on whether it's African or European",
    'answers': [
      'What do you mean? African or European swallow?',
      '11 meters per second',
      '24 mph',
      "I don't know that",
    ],
    'correctAnswer': 'What do you mean? African or European swallow?',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Mad Men, what is Don Draper's real name?",
    'unlockedClue': "It's the name of a man who died in Korea",
    'answers': ['Dick Whitman', 'Donald Draper', 'Richard Sterling', 'Daniel Whitman'],
    'correctAnswer': 'Dick Whitman',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'What color is the pill Neo takes in The Matrix?',
    'unlockedClue': "It's the color associated with truth and awakening",
    'answers': ['Red', 'Blue', 'Green', 'Purple'],
    'correctAnswer': 'Red',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Fargo (TV series), what state is the show primarily set in?',
    'unlockedClue': "It's known for its cold winters and nice people",
    'answers': ['Minnesota', 'North Dakota', 'Wisconsin', 'Montana'],
    'correctAnswer': 'Minnesota',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Princess Bride, what does Inigo Montoya say to the six-fingered man?',
    'unlockedClue': 'It involves his father and preparation to die',
    'answers': [
      'Hello, my name is Inigo Montoya. You killed my father. Prepare to die.',
      'You killed my father!',
      'I am Inigo Montoya',
      'Prepare to die!',
    ],
    'correctAnswer': 'Hello, my name is Inigo Montoya. You killed my father. Prepare to die.',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Sherlock (BBC), what is the name of Sherlock's homeless network?",
    'unlockedClue': "It's named after young street children from the original stories",
    'answers': [
      'The Homeless Network',
      'The Baker Street Irregulars',
      'The Street Network',
      'The Informants',
    ],
    'correctAnswer': 'The Homeless Network',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'What is the name of the fictional African country in Black Panther?',
    'unlockedClue': "It's known for vibranium",
    'answers': ['Wakanda', 'Genosha', 'Latveria', 'Sokovia'],
    'correctAnswer': 'Wakanda',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Office (UK), what is the name of the documentary being filmed?',
    'unlockedClue': "It's simply named after what it's documenting",
    'answers': ['The Office', 'Wernham Hogg', 'Paper Trail', 'Office Life'],
    'correctAnswer': 'The Office',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Pulp Fiction, what is in the briefcase that everyone wants?',
    'unlockedClue': "It's never revealed, but glows golden",
    'answers': ["It's never revealed", 'Gold', 'Diamonds', "Marcellus Wallace's Soul"],
    'correctAnswer': "It's never revealed",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Lost, what are the numbers that appear throughout the series?',
    'unlockedClue': 'There are six numbers that bring bad luck',
    'answers': [
      '4, 8, 15, 16, 23, 42',
      '1, 2, 3, 4, 5, 6',
      '7, 14, 21, 28, 35, 42',
      '3, 6, 9, 12, 15, 18',
    ],
    'correctAnswer': '4, 8, 15, 16, 23, 42',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In How I Met Your Mother, what is Barney's catchphrase?",
    'unlockedClue': 'It expresses that something is awesome',
    'answers': ['Legen... wait for it... dary!', 'Suit up!', 'Awesome!', 'Challenge accepted!'],
    'correctAnswer': 'Legen... wait for it... dary!',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In The Shawshank Redemption, how long was Andy Dufresne's sentence?",
    'unlockedClue': 'It was for double murder',
    'answers': ['Two life sentences', '25 years', 'Life without parole', '50 years'],
    'correctAnswer': 'Two life sentences',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Rick and Morty, what is Rick's favorite alcoholic beverage?",
    'unlockedClue': "It's clear and makes him burp a lot",
    'answers': ['Flask liquid/Alcohol', 'Beer', 'Wine', 'Whiskey'],
    'correctAnswer': 'Flask liquid/Alcohol',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Sopranos, what is the name of Tony's psychiatrist?",
    'unlockedClue': "She's played by Lorraine Bracco",
    'answers': ['Dr. Jennifer Melfi', 'Dr. Sarah Miller', 'Dr. Lisa Hoffman', 'Dr. Maria Romano'],
    'correctAnswer': 'Dr. Jennifer Melfi',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "What movie features the quote 'May the Force be with you'?",
    'unlockedClue': "It's from a galaxy far, far away",
    'answers': ['Star Wars', 'Star Trek', 'Guardians of the Galaxy', 'Blade Runner'],
    'correctAnswer': 'Star Wars',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Brooklyn Nine-Nine, what is Jake Peralta's favorite movie?",
    'unlockedClue': "It's an action movie franchise starring Bruce Willis",
    'answers': ['Die Hard', 'Speed', 'Lethal Weapon', 'The Rock'],
    'correctAnswer': 'Die Hard',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'In The Good Place, what is the name of the ethical philosophy that Eleanor learns about?',
    'unlockedClue': "It's about the greatest good for the greatest number",
    'answers': ['Utilitarianism', 'Deontology', 'Virtue Ethics', 'Existentialism'],
    'correctAnswer': 'Utilitarianism',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Hannibal (TV series), what is Will Graham's job title?",
    'unlockedClue': 'He teaches at the FBI Academy and profiles killers',
    'answers': [
      'FBI Special Investigator and Teacher',
      'Criminal Profiler',
      'FBI Agent',
      'Forensic Psychiatrist',
    ],
    'correctAnswer': 'FBI Special Investigator and Teacher',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In The Lion King, what is Timon and Pumbaa's philosophy called?",
    'unlockedClue': "It means 'no worries' in Swahili",
    'answers': ['Hakuna Matata', 'Carpe Diem', 'Live and Let Live', 'No Problems'],
    'correctAnswer': 'Hakuna Matata',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Blade Runner, what test is used to identify replicants?',
    'unlockedClue': "It's named after a character from the book",
    'answers': ['Voight-Kampff Test', 'Turing Test', 'Blade Test', 'Replicant Test'],
    'correctAnswer': 'Voight-Kampff Test',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Seinfeld, what is Kramer's first name?",
    'unlockedClue': "It's revealed in later seasons and starts with 'C'",
    'answers': ['Cosmo', 'Carl', 'Charlie', 'Chester'],
    'correctAnswer': 'Cosmo',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question':
      'In True Detective (Season 1), what is the name of the cult that Rust and Marty investigate?',
    'unlockedClue': 'They worship a Yellow King',
    'answers': ['The Yellow King Cult', 'Tuttle Family', 'Carcosa Cult', 'The Light Bringers'],
    'correctAnswer': 'Tuttle Family',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'What is the name of the hotel in The Shining?',
    'unlockedClue': "It's located in the Colorado mountains",
    'answers': [
      'The Overlook Hotel',
      'The Stanley Hotel',
      'The Grand Hotel',
      'The Mountain View Hotel',
    ],
    'correctAnswer': 'The Overlook Hotel',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Avatar: The Last Airbender, what is Aang's flying bison's name?",
    'unlockedClue': 'It sounds like a greeting',
    'answers': ['Appa', 'Momo', 'Bumi', 'Toph'],
    'correctAnswer': 'Appa',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In Westworld, what phrase do the hosts say when they're about to malfunction?",
    'unlockedClue': "It's about something not appearing as it seems",
    'answers': [
      'These violent delights have violent ends',
      "It doesn't look like anything to me",
      'Have you ever seen anything so full of splendor?',
      "The maze isn't meant for you",
    ],
    'correctAnswer': "It doesn't look like anything to me",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Twin Peaks, what is the name of Agent Cooper's favorite coffee spot?",
    'unlockedClue': "It's a Double R establishment",
    'answers': ['Double R Diner', 'Great Northern Hotel', "One Eyed Jack's", 'The Bang Bang Bar'],
    'correctAnswer': 'Double R Diner',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Toy Story, what is the name of Andy's favorite toy?",
    'unlockedClue': "There's a snake in his boot",
    'answers': ['Woody', 'Buzz Lightyear', 'Rex', 'Mr. Potato Head'],
    'correctAnswer': 'Woody',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Fight Club, what is the first rule of Fight Club?',
    'unlockedClue': "It's about not talking about something",
    'answers': [
      'You do not talk about Fight Club',
      'No shirts, no shoes',
      'No touching of the hair or face',
      'One fight at a time',
    ],
    'correctAnswer': 'You do not talk about Fight Club',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Fresh Prince of Bel-Air, what city is Will originally from?',
    'unlockedClue':
      "It's where he was born and raised, on the playground is where he spent most of his days",
    'answers': ['Philadelphia', 'New York', 'Chicago', 'Detroit'],
    'correctAnswer': 'Philadelphia',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'In Mr. Robot, what is the name of the hacker group that Elliot joins?',
    'unlockedClue': "They're society's outcasts",
    'answers': ['fsociety', 'Anonymous', 'Dark Army', 'Evil Corp'],
    'correctAnswer': 'fsociety',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In The Godfather, what does Al Pacino's character place on his father's chest?",
    'unlockedClue': "It's a citrus fruit",
    'answers': ['An orange', 'A lemon', 'A lime', 'An apple'],
    'correctAnswer': 'An orange',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In SpongeBob SquarePants, what instrument does Squidward play?',
    'unlockedClue': "It's a woodwind instrument with a reed",
    'answers': ['Clarinet', 'Saxophone', 'Flute', 'Oboe'],
    'correctAnswer': 'Clarinet',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Inception, how many levels deep do they go into dreams?',
    'unlockedClue': "It's the same number of main team members",
    'answers': ['Four levels', 'Three levels', 'Five levels', 'Six levels'],
    'correctAnswer': 'Four levels',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Better Call Saul, what is Jimmy McGill's middle name?",
    'unlockedClue': "It's revealed when he gets his law degree",
    'answers': ['Morgan', 'Michael', 'Matthew', 'Martin'],
    'correctAnswer': 'Morgan',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Back to the Future, what speed does the DeLorean need to reach to time travel?',
    'unlockedClue': "It's the same number as miles per hour",
    'answers': ['88 mph', '55 mph', '100 mph', '77 mph'],
    'correctAnswer': '88 mph',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In House of Cards (US), what is Frank Underwood's home state?",
    'unlockedClue': "It's a southeastern state known for peaches",
    'answers': ['South Carolina', 'Georgia', 'North Carolina', 'Tennessee'],
    'correctAnswer': 'South Carolina',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Forrest Gump, what does Forrest say life is like?',
    'unlockedClue': 'It involves sweet treats and uncertainty',
    'answers': ['A box of chocolates', 'A roller coaster', 'A journey', 'A puzzle'],
    'correctAnswer': 'A box of chocolates',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The Leftovers, what percentage of the world's population disappeared?",
    'unlockedClue': "It's a small single-digit percentage",
    'answers': ['2%', '5%', '3%', '1%'],
    'correctAnswer': '2%',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "In The Dark Knight, what is the Joker's origin story?",
    'unlockedClue': 'The character prefers multiple choice',
    'answers': ['Multiple choice', 'Chemical plant accident', 'Failed comedian', 'Unknown'],
    'correctAnswer': 'Multiple choice',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In Futurama, what is Bender's favorite activity?",
    'unlockedClue': "It involves taking things that don't belong to him",
    'answers': ['Stealing', 'Drinking', 'Smoking', 'Gambling'],
    'correctAnswer': 'Stealing',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Goodfellas, what does Henry Hill say is the worst part about being in prison?',
    'unlockedClue': "It's about the quality of Italian food",
    'answers': [
      'The food - no good tomato sauce',
      'Missing his family',
      'The boredom',
      'No freedom',
    ],
    'correctAnswer': 'The food - no good tomato sauce',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In The X-Files, what is Mulder's sister's name?",
    'unlockedClue': 'She shares her name with a month',
    'answers': ['Samantha', 'Sarah', 'Susan', 'Sandra'],
    'correctAnswer': 'Samantha',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In Finding Nemo, what type of fish is Nemo?',
    'unlockedClue': "It's a colorful tropical fish with distinctive stripes",
    'answers': ['Clownfish', 'Angelfish', 'Goldfish', 'Tropical Fish'],
    'correctAnswer': 'Clownfish',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Taxi Driver, what does Travis Bickle say to his mirror?',
    'unlockedClue': "It's about talking to him",
    'answers': [
      "You talkin' to me?",
      'Are you looking at me?',
      'Who are you?',
      'What do you want?',
    ],
    'correctAnswer': "You talkin' to me?",
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In The Mandalorian, what does everyone call the Child?',
    'unlockedClue': "It's a nickname related to his species",
    'answers': ['Baby Yoda', 'The Child', 'Grogu', 'Little Green Guy'],
    'correctAnswer': 'Baby Yoda',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "In Frasier, what is Niles Crane's ex-wife's name?",
    'unlockedClue': "She's never seen on screen but often mentioned",
    'answers': ['Maris', 'Daphne', 'Roz', 'Lilith'],
    'correctAnswer': 'Maris',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In Casablanca, what does Rick tell Sam to play?',
    'unlockedClue': 'It involves time going by',
    'answers': ['As Time Goes By', 'Moonlight Serenade', 'The Way You Look Tonight', 'Summertime'],
    'correctAnswer': 'As Time Goes By',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "In South Park, what is Cartman's first name?",
    'unlockedClue': "It's also a common first name for boys",
    'answers': ['Eric', 'Kyle', 'Stan', 'Kenny'],
    'correctAnswer': 'Eric',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In The Usual Suspects, who is Keyser Söze?',
    'unlockedClue': "He's been hiding in plain sight",
    'answers': ['Verbal Kint', 'Dean Keaton', 'McManus', 'Fenster'],
    'correctAnswer': 'Verbal Kint',
    'category': 'entertainment',
    'type': 'trivia',
  },

  // sports
  {
    'level': 'easy',
    'question':
      "Which sport is known for the phrase 'It's not whether you win or lose, it's how you play the game'?",
    'unlockedClue':
      'This phrase is often associated with a sport that emphasizes sportsmanship over competition.',
    'answers': ['Football', 'Basketball', 'Baseball', 'Golf'],
    'correctAnswer': 'Baseball',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': 'In which country did the sport of rugby originate?',
    'unlockedClue':
      'This country is known for its love of rugby and has a national team called the All Blacks.',
    'answers': ['England', 'Australia', 'New Zealand', 'South Africa'],
    'correctAnswer': 'England',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'Which extreme sport involves riding a board down a mountain while holding onto a rope attached to a kite?',
    'unlockedClue': 'This sport combines elements of surfing, windsurfing, and paragliding.',
    'answers': ['Kitesurfing', 'Snowboarding', 'Wakeboarding', 'Sandboarding'],
    'correctAnswer': 'Kitesurfing',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'Which UK-based group is credited with pioneering modern bungee jumping in the late 1970s?',
    'unlockedClue':
      'This group made the first modern jumps from the Clifton Suspension Bridge in Bristol.',
    'answers': [
      'The Extreme Sports Club',
      'The Dangerous Sports Club',
      'The Adventure Seekers',
      'The Cliff Divers',
    ],
    'correctAnswer': 'The Dangerous Sports Club',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'Which American football player played in both a Super Bowl and a World Series?',
    'unlockedClue': 'This athlete is known for his dual-sport career in baseball and football.',
    'answers': ['Deion Sanders', 'Bo Jackson', 'Dion Waiters', 'Jim Thorpe'],
    'correctAnswer': 'Deion Sanders',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'Which extreme sport involves ironing clothes in unusual and dangerous locations?',
    'unlockedClue': 'This activity was invented in 1997 in Leicester, England.',
    'answers': ['Extreme ironing', 'Bungee ironing', 'Skydiving laundry', 'Mountain pressing'],
    'correctAnswer': 'Extreme ironing',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'In which year did the first modern Olympic Games take place?',
    'unlockedClue': 'The first modern Olympics were held in this year in Athens, Greece.',
    'answers': ['1896', '1900', '1924', '1932'],
    'correctAnswer': '1896',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "Which sport is known as 'the beautiful game'?",
    'unlockedClue':
      'This sport is played by teams of 11 players and is the most popular sport worldwide.',
    'answers': ['Football (Soccer)', 'Basketball', 'Tennis', 'Cricket'],
    'correctAnswer': 'Football (Soccer)',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "Which US city is home to the famous 'Fenway Park' baseball stadium?",
    'unlockedClue': 'This city is known for its rich sports history and passionate sports fans.',
    'answers': ['New York', 'Chicago', 'Boston', 'Los Angeles'],
    'correctAnswer': 'Boston',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "Which UK football club's fans are known as 'The Toon Army'?",
    'unlockedClue': "This club is based in the northeast of England and plays at St James' Park.",
    'answers': ['Newcastle United', 'Sunderland', 'Middlesbrough', 'Hull City'],
    'correctAnswer': 'Newcastle United',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'Which extreme sport involves descending a river in an inflatable boat?',
    'unlockedClue':
      'This activity is popular in areas with fast-flowing rivers and is often done in teams.',
    'answers': ['Canoeing', 'Rafting', 'Kayaking', 'Boating'],
    'correctAnswer': 'Rafting',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': "Which sport was featured in the 1982 film 'Chariots of Fire'?",
    'unlockedClue': 'The film tells the story of two athletes competing in the 1924 Olympics.',
    'answers': ['Football', 'Athletics (Track and Field)', 'Rowing', 'Cycling'],
    'correctAnswer': 'Athletics (Track and Field)',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'easy',
    'question': "Which sport is played with a round ball and is known for its 'touchdowns'?",
    'unlockedClue': 'This sport is particularly popular in the United States.',
    'answers': ['American Football', 'Rugby', 'Cricket', 'Baseball'],
    'correctAnswer': 'American Football',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question':
      'Which sport involves two teams of six players each trying to score points by hitting a ball over a net?',
    'unlockedClue': 'This sport is played both indoors and on sand courts.',
    'answers': ['Tennis', 'Badminton', 'Volleyball', 'Table Tennis'],
    'correctAnswer': 'Volleyball',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'Which sport was banned in England in 1363 by King Edward III?',
    'unlockedClue': "The ban was due to the sport's interference with archery practice.",
    'answers': ['Football', 'Cricket', 'Hockey', 'Rugby'],
    'correctAnswer': 'Football',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': 'Which extreme sport involves jumping from a great height with a parachute?',
    'unlockedClue': 'This sport is often associated with military training and thrill-seeking.',
    'answers': ['Skydiving', 'Bungee Jumping', 'Hang Gliding', 'Paragliding'],
    'correctAnswer': 'Skydiving',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question':
      'Which sport was originally played by ancient Egyptians and is considered the precursor to modern polo?',
    'unlockedClue': 'The game involved players on horseback hitting a ball with mallets.',
    'answers': ['Polo', 'Hockey', 'Lacrosse', 'Croquet'],
    'correctAnswer': 'Polo',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "Which sport is known for the term 'hat-trick'?",
    'unlockedClue': 'This term is used when a player scores three goals in a single game.',
    'answers': ['Football (Soccer)', 'Ice Hockey', 'Cricket', 'Rugby'],
    'correctAnswer': 'Football (Soccer)',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question': 'Which extreme sport involves riding a bicycle down steep mountain trails?',
    'unlockedClue': 'This sport requires specialized bikes and protective gear.',
    'answers': ['Mountain Biking', 'Road Cycling', 'BMX', 'Cyclo-Cross'],
    'correctAnswer': 'Mountain Biking',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'medium',
    'question': "Which sport is known for the term 'slam dunk'?",
    'unlockedClue':
      'This term is used when a player jumps and scores by putting the ball directly through the hoop.',
    'answers': ['Basketball', 'Volleyball', 'Handball', 'Netball'],
    'correctAnswer': 'Basketball',
    'category': 'entertainment',
    'type': 'trivia',
  },
  {
    'level': 'hard',
    'question':
      'Which sport was first played in ancient Greece and is considered the precursor to modern handball?',
    'unlockedClue': 'The game involved two teams trying to score by throwing a ball into a goal.',
    'answers': ['Handball', 'Football', 'Basketball', 'Volleyball'],
    'correctAnswer': 'Handball',
    'category': 'entertainment',
    'type': 'trivia',
  },
];
